import 'package:dabbler/core/fp/failure.dart';
import 'package:dabbler/core/fp/result.dart';
import 'package:dabbler/core/fp/result_guard.dart';
import 'package:dabbler/data/models/activities/activity_log.dart';
import 'package:dabbler/data/models/activities/activity_log_model.dart';
import '../../domain/repositories/activity_log_repository.dart';
import '../datasources/activity_log_remote_data_source.dart';

/// Implementation of ActivityLogRepository
class ActivityLogRepositoryImpl implements ActivityLogRepository {
  final ActivityLogRemoteDataSource remoteDataSource;

  ActivityLogRepositoryImpl({required this.remoteDataSource});

  @override
  Future<Result<List<ActivityLog>, Failure>> getUserActivities({
    required String userId,
    ActivityType? type,
    String? category,
    DateTime? startDate,
    DateTime? endDate,
    int page = 1,
    int limit = 50,
  }) {
    return guardResult(() async {
      final List<ActivityLog> activities = await remoteDataSource.getUserActivities(
        userId: userId,
        type: type,
        category: category,
        startDate: startDate,
        endDate: endDate,
        page: page,
        limit: limit,
      );
      return activities;
    });
  }

  @override
  Future<Result<Map<String, int>, Failure>> getUserActivityStats({
    required String userId,
    DateTime? startDate,
    DateTime? endDate,
  }) {
    return guardResult(() async {
      final stats = await remoteDataSource.getUserActivityStats(
        userId: userId,
        startDate: startDate,
        endDate: endDate,
      );
      return stats;
    });
  }

  @override
  Future<Result<ActivityLog, Failure>> createActivity({
    required String userId,
    required ActivityType type,
    String? subType,
    required String title,
    String? description,
    ActivityStatus? status,
    String? targetId,
    String? targetType,
    String? targetUserId,
    String? targetUserName,
    String? targetUserAvatar,
    String? venue,
    String? location,
    double? amount,
    String? currency,
    int? points,
    int? count,
    DateTime? scheduledDate,
    Map<String, dynamic>? metadata,
    String? iconUrl,
    String? thumbnailUrl,
    String? actionRoute,
  }) {
    return guardResult(() async {
      final activity = ActivityLogModel(
        id: '', // Will be generated by database
        userId: userId,
        type: type,
        subType: subType,
        title: title,
        description: description,
        status: status ?? ActivityStatus.completed,
        targetId: targetId,
        targetType: targetType,
        targetUserId: targetUserId,
        targetUserName: targetUserName,
        targetUserAvatar: targetUserAvatar,
        venue: venue,
        location: location,
        amount: amount,
        currency: currency,
        points: points,
        count: count,
        createdAt: DateTime.now(),
        scheduledDate: scheduledDate,
        metadata: metadata,
        iconUrl: iconUrl,
        thumbnailUrl: thumbnailUrl,
        actionRoute: actionRoute,
      );

      final result = await remoteDataSource.createActivity(activity);
      return result;
    });
  }

  @override
  Future<Result<ActivityLog, Failure>> updateActivity({
    required String activityId,
    ActivityStatus? status,
    String? description,
    Map<String, dynamic>? metadata,
  }) {
    return guardResult(() async {
      final result = await remoteDataSource.updateActivity(
        activityId: activityId,
        status: status,
        description: description,
        metadata: metadata,
      );

      return result;
    });
  }

  @override
  Future<Result<bool, Failure>> deleteActivity(String activityId) {
    return guardResult(() async {
      final result = await remoteDataSource.deleteActivity(activityId);
      return result;
    });
  }

  @override
  Future<Result<Map<String, List<ActivityLog>>, Failure>> getActivitiesByDateRange({
    required String userId,
    required DateTime startDate,
    required DateTime endDate,
  }) async {
    final activitiesResult = await guardResult(() async {
      final List<ActivityLog> activities = await remoteDataSource.getUserActivities(
        userId: userId,
        startDate: startDate,
        endDate: endDate,
        limit: 1000,
      );
      return activities;
    });

    if (activitiesResult.isFailure) {
      return Err<Map<String, List<ActivityLog>>, Failure>(
        activitiesResult.requireError,
      );
    }

    final activities = activitiesResult.requireValue;

    final Map<String, List<ActivityLog>> grouped = {
      'Today': [],
      'Yesterday': [],
      'This Week': [],
      'This Month': [],
      'Older': [],
    };

    for (final activity in activities) {
      grouped[activity.formattedDate]?.add(activity);
    }

    return Ok<Map<String, List<ActivityLog>>, Failure>(grouped);
  }

  @override
  Future<Result<List<ActivityLog>, Failure>> getRecentActivities({
    required String userId,
    int days = 7,
  }) {
    return guardResult(() async {
      final startDate = DateTime.now().subtract(Duration(days: days));
      final List<ActivityLog> activities = await remoteDataSource.getUserActivities(
        userId: userId,
        startDate: startDate,
        limit: 100,
      );

      return activities;
    });
  }

  @override
  Future<Result<Map<String, int>, Failure>> getCategoryStats(String userId) {
    return guardResult(() async {
      final stats = await remoteDataSource.getCategoryStats(userId);
      return stats;
    });
  }
}
